---
# COMP90024 Assignment 2
# Team: 38
# City: Melbourne
# Members:
# Ziran Gu (1038782)
# Jueying Wang (1016724)
# Yifei Zhou(980429)
# Jiakai Ni (988303)
# Ziyue Liu (1036109)

# common vars
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal
instance_image: 916cad7a-c545-48b2-b36c-d509ee63b3ce # ubuntu 18.04 with docker
instance_key_name: group38 # ssh private key
project_working_directory: /Users/likwuncheung/repos/ansible/ansible

# volumes configuration
volumes:
  - name: group38-volume1
    size: 150
  - name: group38-volume2
    size: 150
  - name: group38-volume3
    size: 150
  - name: group38-volume4
    size: 50

#  security group
security_groups:
  - name: ssh
    description: "security group for ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: http
    description: "security group for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: anyremote
    description: "security group for access from port 1024 to 32767"
    protocol: tcp
    port_range_min: 1024
    port_range_max: 32767
    remote_ip_prefix: 0.0.0.0/0

#  instance configuration
instances:
  - name: group38-instance1
    flavor: uom.mse.2c9g
    volumes: ["group38-volume1"]
    device: /dev/vdb
    mountpoint: /vdata

  - name: group38-instance2
    flavor: uom.mse.2c9g
    volumes: ["group38-volume2"]
    device: /dev/vdb
    mountpoint: /vdata

  - name: group38-instance3
    flavor: uom.mse.2c9g
    volumes: ["group38-volume3"]
    device: /dev/vdb
    mountpoint: /vdata

  - name: group38-instance4
    flavor: uom.mse.1c4g
    volumes: ["group38-volume4"]
    device: /dev/vdb
    mountpoint: /data
