- hosts: localhost
  vars_files:
    - vars/local_vars.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volumes
    - role: openstack-security-groups
    - role: openstack-instances
